style = "yas"
always_use_return = true
indent = 4
margin = 100
always_for_in = true
remove_extra_newlines = true
short_to_long_function_def = true
whitespace_in_kwargs = false
annotate_untyped_fields_with_any = true
format_docstrings = false
separate_kwargs_with_semicolon = true
surround_whereop_typeparameters = true
whitespace_ops_in_indices = true
align_assignment = true
align_conditional = true
align_pair_arrow = true
align_matrix = false
import_to_using = false
