"""
    ρ(d::AbstractVector, cap::Intersection)

Return an upper bound on the support function of the intersection of two sets in
a given direction.

### Input

- `d`   -- direction
- `cap` -- intersection of two sets

### Output

An upper bound on the support function in the given direction.

### Algorithm

The support function of an intersection of ``X`` and ``Y`` is upper-bounded by
the minimum of the support-function evaluations for ``X`` and ``Y``.
"""
@validate function ρ(d::AbstractVector, cap::Intersection)
    return _ρ_min(d, cap)
end

function _ρ_min(d::AbstractVector, cap::Intersection)
    return min(ρ(d, cap.X), ρ(d, cap.Y))
end

function ρ_helper(d::AbstractVector{M},
                  cap::Intersection{N,S1,<:Union{HalfSpace{N},Hyperplane{N},Line2D{N}}},
                  algorithm::String; kwargs...) where {M,N,S1}
    if !isbounded(cap.X)
        throw(ArgumentError("the first set in the intersection must be bounded"))
    end
    X = cap.X # compact set
    H = cap.Y # half-space or hyperplane or line

    # if the intersection is empty => stop
    if isempty(cap)
        throw(ArgumentError("the intersection is empty"))
    end

    if !use_precise_ρ(cap) || algorithm == "simple"
        return _ρ_min(d, cap)
    elseif algorithm == "line_search"
        (s, _) = _line_search(d, X, H; kwargs...)
        return s
    elseif algorithm == "projection"
        @assert H isa Hyperplane || H isa Line2D "the algorithm $algorithm " *
                                                 "cannot be used with a $(typeof(H)); it only works with hyperplanes"
        return _projection(d, X, H; kwargs...)
    else
        throw(ArgumentError("algorithm $algorithm unknown"))
    end
end

"""
    use_precise_ρ(cap::Intersection)

Check whether a precise algorithm for computing ``ρ`` shall be applied.

### Input

- `cap` -- intersection of two sets

### Output

`true` if a precise algorithm shall be applied.

### Notes

The default implementation always returns `true`.

If the result is `false`, a coarse approximation of the support function is
returned.

This function can be overwritten by the user to control the policy.
"""
function use_precise_ρ(cap::Intersection)
    return true
end

"""
    ρ(d::AbstractVector, cap::Intersection{N, S1, S2};
      algorithm::String="line_search", kwargs...
     ) where {N, S1<:LazySet,
                 S2<:Union{HalfSpace, Hyperplane, Line2D}}

Evaluate the support function of the intersection of a compact set and a
half-space/hyperplane/line in a given direction.

### Input

- `d`         -- direction
- `cap`       -- lazy intersection of a compact set and a half-space/hyperplane/
                 line
- `algorithm` -- (optional, default: `"line_search"`): the algorithm to
                 calculate the support function; valid options are:

    * `"line_search"` -- solve the associated univariate optimization problem
                         using a line-search method (either Brent or the
                         Golden Section method)
    * `"projection"`  -- only valid for intersection with a hyperplane/line;
                         evaluate the support function by reducing the problem
                         to the 2D intersection of a rank-2 linear
                         transformation of the given compact set in the plane
                         generated by the given direction `d` and the
                         hyperplane's normal vector `n`
    * `"simple"`      -- take the ``\\min`` of the support-function evaluation
                         of each operand

### Output

The scalar value of the support function of the set `cap` in the given
direction.

### Notes

It is assumed that the first set of the intersection (`cap.X`) is compact.

Any additional number of arguments to the algorithm backend can be passed as
keyword arguments.

### Algorithm

The algorithms are based on solving the associated optimization problem

```math
\\min_{λ ∈ D_h} ρ(ℓ - λa, X) + λb.
```
where ``D_h = \\{ λ : λ ≥ 0 \\}`` if ``H`` is a half-space or
``D_h = \\{ λ : λ ∈ ℝ \\}`` if ``H`` is a hyperplane.

For additional information we refer to [FrehseR12, LeGuernic09, RockafellarW98](@citet)
"""
@validate function ρ(d::AbstractVector, cap::Intersection{N,S1,S2};
                     algorithm::String="line_search",
                     kwargs...) where {N,S1<:LazySet,
                                       S2<:Union{HalfSpace,Hyperplane,Line2D}}
    return ρ_helper(d, cap, algorithm; kwargs...)
end

# symmetric method
@validate function ρ(d::AbstractVector, cap::Intersection{N,S1,S2};
                     algorithm::String="line_search",
                     kwargs...) where {N,S1<:Union{HalfSpace,Hyperplane,Line2D},
                                       S2<:LazySet}
    return ρ_helper(d, swap(cap), algorithm; kwargs...)
end

"""
    ρ(d::AbstractVector, cap::Intersection{N, S1, S2};
      kwargs...) where {N, S1<:LazySet, S2<:AbstractPolyhedron}

Return an upper bound on the support function of the intersection between a
compact set and a polyhedron along a given direction.

### Input

- `d`      -- direction
- `cap`    -- intersection of a compact set and a polyhedron
- `kwargs` -- additional arguments that are passed to the support-function
              algorithm

### Output

An upper bound of the support function of the given intersection.

### Algorithm

The idea is to solve the univariate optimization problem `ρ(di, X ∩ Hi)` for
each half-space in the polyhedron and then take the minimum. This gives an
overapproximation of the exact support value.

This algorithm is inspired from [FrehseR12](@citet).

### Notes

This method relies on the `constraints_list` of the polyhedron.
"""
@validate function ρ(d::AbstractVector, cap::Intersection{N,S1,S2};
                     kwargs...) where {N,S1<:LazySet,S2<:AbstractPolyhedron}
    return ρ_helper(d, cap; kwargs...)
end

# symmetric method
@validate function ρ(d::AbstractVector, cap::Intersection{N,S1,S2};
                     kwargs...) where {N,S1<:AbstractPolyhedron,S2<:LazySet}
    return ρ_helper(d, swap(cap); kwargs...)
end

# disambiguation
@validate function ρ(d::AbstractVector, cap::Intersection{N,S1,S2};
                     kwargs...) where {N,S1<:AbstractPolytope,S2<:AbstractPolyhedron}
    return ρ_helper(d, cap; kwargs...)
end

function ρ_helper(d::AbstractVector, cap::Intersection{N,S1,S2};
                  kwargs...) where {N,S1<:LazySet,S2<:AbstractPolyhedron}
    if !use_precise_ρ(cap)
        use_simple_method = true
    else
        options = Dict(kwargs)
        use_simple_method = haskey(options, :algorithm) &&
                            options[:algorithm] == "simple"
    end

    if use_simple_method
        # simple algorithm
        return _ρ_min(d, cap)
    end

    # more precise algorithm
    @assert isbounded(cap.X) "the first set in the intersection must be bounded"
    return minimum([ρ(d, cap.X ∩ Hi; kwargs...)
                    for Hi in constraints_list(cap.Y)])
end

"""
    ρ(d::AbstractVector, cap::Intersection{N, S1, S2}; kwargs...
     ) where {N, S1<:AbstractPolyhedron, S2<:AbstractPolyhedron}

Evaluate the support function of the intersection between two polyhedral sets.

### Input

- `d`      -- direction
- `cap`    -- intersection of two polyhedral sets
- `kwargs` -- additional arguments that are passed to the support-function
              algorithm

### Output

The evaluation of the support function in the given direction.

### Algorithm

We combine the constraints of the two polyhedra to a new `HPolyhedron`, for
which we then evaluate the support function.
"""
@validate function ρ(d::AbstractVector, cap::Intersection{N,S1,S2};
                     kwargs...) where {N,S1<:AbstractPolyhedron,S2<:AbstractPolyhedron}
    return ρ(d, HPolyhedron([constraints_list(cap.X); constraints_list(cap.Y)]))
end

# disambiguation
@validate function ρ(d::AbstractVector, cap::Intersection{N,S1,S2};
                     algorithm::String="line_search",
                     kwargs...) where {N,S1<:AbstractPolytope,
                                       S2<:Union{HalfSpace,Hyperplane,Line2D}}
    return ρ_helper(d, cap, algorithm; kwargs...)
end

# symmetric method
@validate function ρ(d::AbstractVector, cap::Intersection{N,S1,S2};
                     algorithm::String="line_search",
                     kwargs...) where {N,S1<:Union{HalfSpace,Hyperplane,Line2D},
                                       S2<:AbstractPolytope}
    return ρ_helper(d, swap(cap), algorithm; kwargs...)
end

# disambiguation
@validate function ρ(d::AbstractVector, cap::Intersection{N,S1,S2};
                     algorithm::String="line_search",
                     kwargs...) where {N,S1<:AbstractPolyhedron,
                                       S2<:Union{HalfSpace,Hyperplane,Line2D}}
    return ρ(d, HPolyhedron([constraints_list(cap.X); constraints_list(cap.Y)]))
end

# symmetric method
@validate function ρ(d::AbstractVector, cap::Intersection{N,S1,S2};
                     algorithm::String="line_search",
                     kwargs...) where {N,S1<:Union{HalfSpace,Hyperplane,Line2D},
                                       S2<:AbstractPolyhedron}
    return ρ(d, HPolyhedron([constraints_list(cap.X); constraints_list(cap.Y)]))
end

# disambiguation
@validate function ρ(d::AbstractVector, cap::Intersection{N,S1,S2};
                     algorithm::String="line_search",
                     kwargs...) where {N,S1<:Union{HalfSpace,Hyperplane,Line2D},
                                       S2<:Union{HalfSpace,Hyperplane,Line2D}}
    return ρ(d, HPolyhedron([constraints_list(cap.X); constraints_list(cap.Y)]))
end

"""
    _line_search(ℓ, X, H::Union{<:HalfSpace, <:Hyperplane, <:Line2D}; [kwargs...])

Given a convex set ``X`` and a half-space ``H = \\{x: a^T x ≤ b \\}`` or a
hyperplane/line ``H = \\{x: a^T x = b \\}``, calculate:

```math
\\min_{λ ∈ D_h} ρ(ℓ - λa, X) + λb.
```
where ``D_h = \\{ λ : λ ≥ 0 \\}`` if ``H`` is a half-space or
``D_h = \\{ λ : λ ∈ ℝ \\}`` if ``H`` is a hyperplane.

### Input

- `ℓ` -- direction
- `X` -- convex set
- `H` -- half-space or hyperplane or line

### Output

The tuple `(fmin, λmin)`, where `fmin` is the minimum value of the function
``f(λ) = ρ(ℓ - λa) + λb`` over the feasible set ``λ ≥ 0``, and ``λmin`` is the
minimizer.

### Notes

This function requires the `Optim` package, and relies on the univariate
optimization interface `Optim.optimize(...)`.

Additional arguments to the `optimize` backend can be passed as keyword
arguments. The default method is `Optim.Brent()`.

### Examples

```jldoctest _line_search
julia> X = Ball1(zeros(2), 1.0);

julia> H = HalfSpace([-1.0, 0.0], -1.0);  # x >= 1

julia> using Optim

julia> using LazySets: _line_search

julia> v = _line_search([1.0, 0.0], X, H);  # uses Brent's method by default

julia> v[1]
1.0
```

We can specify the upper bound in Brent's method:

```jldoctest _line_search
julia> v = _line_search([1.0, 0.0], X, H, upper=1e3);

julia> v[1]
1.0
```

Instead of Brent's method we can use the Golden Section method:

```jldoctest _line_search
julia> v = _line_search([1.0, 0.0], X, H, upper=1e3, method=GoldenSection());

julia> v[1]
1.0
```
"""
function _line_search(ℓ, X::LazySet, H::Union{<:HalfSpace,<:Hyperplane,<:Line2D};
                      kwargs...)
    return _line_search_optim(ℓ, X, H; kwargs...)
end

function _line_search_optim(ℓ, X, H; kwargs...)
    mod = Base.get_extension(@__MODULE__, :OptimExt)
    require(mod, :Optim; fun_name="ρ", explanation="(algorithm \"line_search\")")
    error()
end

"""
    _projection(ℓ, X::LazySet, H::Union{Hyperplane, Line2D};
                [lazy_linear_map]=false,
                [lazy_2d_intersection]=true,
                [algorithm_2d_intersection]=nothing,
                [kwargs...])

Given a convex set ``X`` and a hyperplane ``H = \\{x: n ⋅ x = γ \\}``, calculate
the support function of the intersection between the rank-2 projection
``Π_{nℓ} X`` and the line ``Lγ = \\{(x, y): x = γ \\}``.

### Input

- `ℓ`                    -- direction
- `X`                    -- convex set
- `H`                    -- hyperplane
- `lazy_linear_map`      -- (optional, default: `false`) flag to perform the
                            projection lazily or concretely
- `lazy_2d_intersection` -- (optional, default: `true`) flag to perform the 2D
                            intersection between the projected set and the line
                            lazily or concretely
- `algorithm_2d_intersection` -- (optional, default: `nothing`) if given, fixes
                                 the support-function algorithm used for the
                                 intersection in 2D; otherwise the default is
                                 used

### Output

The evaluation of the support function of ``X ∩ H`` along direction ``ℓ``.

### Algorithm

This projection method is based on Prop. 8.2, [1, page 103].

In the original algorithm, [LeGuernic09; Section 8.2](@citet), the linear map is performed
concretely and the intersection is performed lazily (these are the default
options in this algorithm, but here the four combinations are available).
If the set ``X`` is a zonotope, its concrete projection is again a zonotope
(sometimes called "zonogon"). The intersection between this zonogon and the line
can be taken efficiently in a lazy way (see [LeGuernic09; Section 8.2.2](@cite)),
if one uses dispatch on `ρ(y_dir, Sℓ⋂Lγ; kwargs...)` given that `Sℓ` is itself
a zonotope.

### Notes

This function depends on the calculation of the support function of another set
in two dimensions. Obviously one does not want to use `algorithm="projection"`
again for this second calculation. The option `algorithm_2d_intersection` is
used for that: if not given, the default support-function algorithm is used
(e.g., `"line_search"`). You can still pass additional arguments to the
`"line_search"` backend through the `kwargs` arguments.
"""
function _projection(ℓ, X::LazySet, H::Union{Hyperplane,Line2D};
                     lazy_linear_map=false,
                     lazy_2d_intersection=true,
                     algorithm_2d_intersection=nothing,
                     kwargs...)
    @assert isconvex(X) "the first set in the intersection must be convex"

    N = promote_type(eltype(X), eltype(H))
    n = H.a                  # normal vector to the hyperplane
    γ = H.b                  # displacement of the hyperplane
    Πnℓ = vcat(n', ℓ')       # projection map

    x_dir = [one(N), zero(N)]
    y_dir = [zero(N), one(N)]

    Lγ = Line2D(x_dir, γ)

    Xnℓ = lazy_linear_map ? LinearMap(Πnℓ, X) : linear_map(Πnℓ, X)
    Xnℓ⋂Lγ = lazy_2d_intersection ? Intersection(Xnℓ, Lγ) : intersection(Xnℓ, Lγ)

    if isnothing(algorithm_2d_intersection)
        return ρ(y_dir, Xnℓ⋂Lγ; kwargs...)
    else
        return ρ(y_dir, Xnℓ⋂Lγ; algorithm=algorithm_2d_intersection, kwargs...)
    end
end
