name: Spell Check

on:
  pull_request:
  workflow_dispatch:

jobs:
  typos-check:
    name: check spelling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v4
      - name: Check spelling
        uses: crate-ci/typos@master
