# https://github.com/crate-ci/typos
name: Spell check
on:
  pull_request:
  workflow_dispatch:
concurrency:
  # cancel intermediate builds
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  spell-check:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Check spelling
        uses: crate-ci/typos@master
