# https://github.com/julia-actions/julia-runtest
name: Test
on:
  pull_request:
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
  workflow_dispatch:
concurrency:
  # cancel intermediate builds
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1'
        os:
          - ubuntu-latest
          - windows-latest
        arch:
          - x64
        include:
          - version: '1.6'  # test on oldest supported version
            arch: x64
            os: ubuntu-latest
    env:
      JULIA_PKG_SERVER: ''
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - name: Cache artifacts
        uses: julia-actions/cache@v2
      - name: Build package
        uses: julia-actions/julia-buildpkg@v1
      - name: Run tests
        uses: julia-actions/julia-runtest@v1
        timeout-minutes: 35  # kill stale process earlier
      - name: Process coverage
        uses: julia-actions/julia-processcoverage@v1
      - name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          files: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
